// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AurInfo } from "./AurInfo";
import type { BaseInfo } from "./BaseInfo";

export type FullInfo = { Base: BaseInfo } | { Aur: AurInfo };