// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PopularInfo { repo: string, name: string, version: string, description: string, votes: number, popularity: string, }