// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SearchInfo { repo: string, name: string, version: string, download_size: string | null, installed_size: string | null, votes: string | null, popularity: string | null, installed: boolean, description: string, out_of_date: boolean, }