name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  changes:
    name: CI / Filter
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      tauri: ${{ steps.filter.outputs.tauri }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            tauri:
              - 'src-tauri/**'

  test-tauri:
    name: CI / Tauri
    needs: changes
    if: ${{ needs.changes.outputs.tauri == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Restore Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.system.target }}
          override: true
      - name: Install extra dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt update -y
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  frontend:
    name: CI / Vite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Run Build
        run: yarn build