name: Continuous Delivery / Release Git

on:
  workflow_dispatch:

jobs:
  publish:
    name: CD / PKGBUILD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
     
      - name: Build PKGBUILD
        run: ./scripts/base.sh

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: parrot-git
          pkgbuild: ./build/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
